name: Sync to Azure DevOps old

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Azure DevOps CLI
      run: |
        az extension add --name azure-devops --upgrade --yes
    
    - name: Create Project and Repository if Needed
      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        ORG_URL="https://dev.azure.com/guymicciche"
        PROJECT="${{ github.event.repository.name }}"   # 👈 choose what project you want
        REPO_NAME="${{ github.event.repository.name }}"

        # Configure defaults
        az devops configure --defaults organization=$ORG_URL project=$PROJECT

        # Ensure project exists
        if ! az devops project show --project "$PROJECT" >/dev/null 2>&1; then
          echo "Creating project: $PROJECT"
          az devops project create --name "$PROJECT" --organization $ORG_URL
          echo "✅ Project created: $PROJECT"
        else
          echo "Project $PROJECT already exists"
        fi

        # Ensure repo exists
        if ! az repos show --repository "$REPO_NAME" >/dev/null 2>&1; then
          echo "Creating repository: $REPO_NAME"
          az repos create --name "$REPO_NAME"
          echo "✅ Repository created: $REPO_NAME"
        else
          echo "Repository $REPO_NAME already exists"
        fi
    
    - name: Sync to Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        ORG_URL="https://dev.azure.com/guymicciche"
        PROJECT="${{ github.event.repository.name }}"
        REPO_NAME="${{ github.event.repository.name }}"

        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        # Add Azure DevOps remote
        git remote add azure https://$AZURE_DEVOPS_PAT@dev.azure.com/guymicciche/$PROJECT/_git/$REPO_NAME || true
        
        git push azure --all --force
        git push azure --tags --force

        echo "✅ Synced $REPO_NAME to Azure DevOps"
