            - name: Sync to Azure DevOps
  # You may pin to the exact commit or the version.
  # uses: GuyMicciche/SyncToAzureDevOps@eed98edc72949a08343cd8b558b913aefc555ee6
  uses: GuyMicciche/SyncToAzureDevOps@v1.0.0
  with:
    # Azure DevOps URL & organization name (e.g., https://dev.azure.com/myorg)
    organization: 
    # Azure DevOps Personal Access Token (with Project and Code permissions)
    pat: 
          
