name: Sync GitHub to Azure DevOps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Azure DevOps
        uses: GuyMicciche/SyncToAzureDevOps@v1.0.1
        with:
          # Only the org name, PAT comes from secrets
          organization: "https://dev.azure.com/guymicciche"
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
