name: Sync to Azure DevOps

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger button

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history
    
    - name: Setup Azure DevOps CLI
      run: |
        az extension add --name azure-devops --upgrade --yes
    
    - name: Create or Update Repository
      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        REPO_NAME="${{ github.event.repository.name }}"
        REPO_DESC="${{ github.event.repository.description }}"
        PROJECT="MyProjectName"   # 👈 change this to your real project name

        # Configure organization (PAT comes from env automatically)
        az devops configure --defaults organization=https://dev.azure.com/guymicciche project=$PROJECT

        # Check if repo exists
        if ! az repos show --repository "$REPO_NAME" >/dev/null 2>&1; then
          echo "Creating repository: $REPO_NAME"
          az repos create --name "$REPO_NAME"
          echo "✅ Repository created: $REPO_NAME"
        else
          echo "Repository $REPO_NAME already exists"
        fi
    
    - name: Sync to Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        REPO_NAME="${{ github.event.repository.name }}"
        PROJECT="MyProjectName"  # 👈 same project name as above

        # Configure git
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add Azure DevOps remote
        git remote add azure https://$AZURE_DEVOPS_PAT@dev.azure.com/guymicciche/$PROJECT/_git/$REPO_NAME
        
        # Push to Azure DevOps
        git push azure --all --force
        git push azure --tags --force

        echo "✅ Synced $REPO_NAME to Azure DevOps"
